group_name: "group_name" #moveit move group name  ***CHANGE IT***
base_link: "base_link"    #***CHANGE IT***
last_link: "last_link"    #***CHANGE IT***

display_step_by_step: false  #if true it shows the algorithm execution step by step, with paths and intermediate solutions visualization
number_paths: 4 #number of pre-computed paths
max_time_for_replanning: 0.1 #maximum time for replanning, in seconds
start_configuration: [0.0, 0.0, 0.0] #starting robot configuration
stop_configuration: [0.8, 0.8, 0.8]  #ending robot configuration
number_of_connection_on_which_current_conf_is: 3 #the number of the connection of the robot current path on which placing the current robot configuration
