test_name: "sharework"
group_name: "manipulator"
base_link: "base_link"
last_link: "open_tip"
dt_replan_restricted: 0.100
dt_replan_relaxed: 0.150
checker_resolution: 0.05
trj_execution_thread_frequency: 500
collision_checker_thread_frequency: 25
init_test: 0
end_test: 1
opt_path: true
display_timing_warning: true
display_replanning_success: true
starting_obs_pos: [0.6,0.0,1.4]

scaling: 1.0
checker_resolution: 0.05
start_configuration:  [2.3905274868011475, -0.8789189618876954, 1.0315025488482874, -1.7170521221556605, 1.555264949798584, -2.4404378573047083]
stop_configuration: [0.5304203033447266, -0.84785349786792, 1.0433624426471155, -1.7949758968748988, 1.5526299476623535, -2.712820355092184]
read_safe_scaling: true
get_real_start_pos: false
